### ISSUE TITLE
Resume Generation

### ISSUE THREAD

**Issue by scalarmotion** [CS2103-AY1819S1-W17-1/main#25]
Feature to generate a resume in Markdown containing information from saved entries based on a template.

### Subtasks:

**V1.1: No entries, fixed default template**
- [ ] Add Resume class
- [ ] Add MakeCommand class
- [ ] Set up API to receive a Template object
- [ ] Integrate Markdown library to convert a Template object to a Resume object, containing a string of Markdown and other metadata for the resume
- [ ] Open a file in storage using the Resume object and output the Markdown into it
