### ISSUE TITLE
As a SoC student, I want my resume generator to understand common SoC / NUS slang

### ISSUE THREAD

**Issue by anubh-v** [CS2103-AY1819S1-W17-1/main#35]
- [x] Add an Awareness class, which will manage all contextual information for the application. #74 

- [x] Add ability to de-serialise user defined XML data into an Awareness object. #73 

- [x] Add high level AwarenessStorage API #75 

- [ ] Trigger de-serialisation of `slang - full phrase` mappings (via Storage) during application initialisation 
__(Note: Basic validation of mappings will be done in v1.2)__

- [ ] Pass the created Awareness object to Model during application initialisation.

- [x] Load sample 'slang - full phrase' mappings into Awareness object #99 

- [x] Add ContextCommand and ContextCommandParser, to allow user to type `nus <expression>`. For example, the user may type `nus ug research opp prog` #76 

- [x] Add ability to convert a given `expression` to a `possible Event Name` #9 

- [x] Accept user provided `expression`, and display the `possible Event Name` #109
