### ISSUE TITLE
Managing and displaying data for `ResumeEntry`

### ISSUE THREAD

**Issue by jhengy** [CS2103-AY1819S1-W17-1/main#37]
Part I
- [x] feature to create `ResumeEntry` Objects 
  - [x] add `addEntry` command : #77 v1.3  (1)

Part II
- [x] features associated with display of entry in UI
  - [x] integrating Model.EntryBook into UI #164
  - [x] `selectEntry` command  v1.3 (3) issue #145

Part III
- [x] features associated with manipulating EntryBook 
  - [x] `addBullet` command v1.3 (2) issue #144 
  - [x] `editEntry` command issue #272 
  - [x] `deleteEntry` command issue #269

Part IV 
- [x] fine-tuning of UI
   - ui modification for product demo #277 
  - ui iprovement after product demo #288 

===========================
To be completed in v2.0
Part VI
- [ ] fine tuning of UI to enhance UX
  - [ ] Creating A separate display for minor entries( issue #202 )
  - [ ] Allowing Users to to omit subtitles when adding entries (issue #225)

Part V
  - [ ] integrate Storage Component to all the commands implemented to allow for local storage of entries #192
  - [ ] `editBullet` command 
  - [ ] `deleteBullet` command issue 
Part V 
- UI color coding of tags?
Part VI
 - [ ] undo/redo feature integration of entrybook #175
