### ISSUE TITLE
Contexual Awareness

### ISSUE THREAD

**Issue by anubh-v** [CS2103-AY1819S1-W17-1/main#68]
- [ ]  #35 As a SoC student, I want the my resume generator to understand common NUS / SoC slang

- [ ] #69 As a SoC student, I want my resume to automatically contain descriptions of common SOC programmes 

- [ ] As a user, I want to my tools to provide dropdown options based on my input

- [ ] As a SoC student, I want to pick standard SOC awards (Honour Roll, etc) from a list rather than type them out manually
