### ISSUE TITLE
AddEntry Command: As a student, I want to save pieces of information about my relevant experience easily into ResuMaker, which is to be shown

### ISSUE THREAD

**Issue by jhengy** [CS2103-AY1819S1-W17-1/main#77]
-  sub-tasks :
    - [x]  parse user input command and generate `ResumeEntry` and `addEntryCommand` Object  #49 
    - [x]  allowing the addition of minorEntries := entries without title, subtitle and duration, but just contain `Category` and `EntryDescription` #49 
    - [x]  store added entry in Model and update all states in Model #81 
        - merge and push #84 for uniqueEntryList
        - EntryBook and ReadOnlyEntryBook with test (probably need EntryBookBuilder as well) (#79 )
        - VersionedEntryBook with test (#92)
        - ModelManager changes to use VersionedEntryBook (major tests everywhere 😢) (#93)
        - model to commit EntryBook when entry is added #(#165)

 

 how are they organized?? Still unable to draw the dot between model and ui
from developer's guide: " Binds itself to some data in the Model so that the UI can auto-update when data in the Model change."

**Comment by anubh-v** [comment]
Will be better to use the "As a user, ..." format for the title
